/*
 * The CycloneDX view of the Windows PDFium renderer runtime under
 * `vendor/pdfium/runtime/`.
 *
 * `SBOM.cdx.json` is otherwise generated from `package-lock.json`, so it
 * describes npm dependencies and nothing else. PDFium is a prebuilt binary
 * from official Google Chromium PDFium releases via bblanchon/pdfium-binaries,
 * and none of that had a component. The notices shipped describe every bundled
 * license, so this was never a licence-compliance failure — but a bill of
 * materials that omits the native code in the Windows bundle misleads whoever
 * consumes it.
 *
 * Everything below is DERIVED from `vendor/pdfium/runtime.provenance.json`,
 * which is generated by `scripts/vendor-pdfium-runtime.mjs` from a download
 * and verification against `sources.lock.json`. Nothing here restates a
 * version, a digest or a licence that is written down somewhere else: a
 * component list maintained by hand would drift from the lock the first time
 * anyone bumped a source, which is exactly the failure this repository keeps
 * paying for. `test/pdfium-runtime-artifact.test.js` verifies that the
 * committed runtime bytes and notice manifest match this provenance.
 *
 * What counts as a component, and why:
 *
 *   - PDFium and every bundled library (FreeType, libpng, zlib, Little CMS,
 *     libjpeg-turbo, OpenJPEG, ICU, Abseil, LLVM libc, simdutf, fast_float,
 *     Anti-Grain Geometry) are compiled into the pdfium.dll binary that ships
 *     and are redistributed with it. Their code is linked into the binary, so
 *     they are components, each hashed against the source archive or build
 *     digest that produced them.
 */

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");

export const PDFIUM_RUNTIME_PROVENANCE_PATH = "vendor/pdfium/runtime.provenance.json";

export const PDFIUM_RUNTIME_PROVENANCE = Object.freeze(JSON.parse(readFileSync(
  path.join(REPO_ROOT, ...PDFIUM_RUNTIME_PROVENANCE_PATH.split("/")),
  "utf8",
)));

const RUNTIME_DIRECTORY = "vendor/pdfium/runtime";
const RUNTIME_BOM_REF = "urn:pdf-tools:pdfium-runtime";

function compareCodePoints(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function purlSegment(value) {
  return value.split("/").map(part => encodeURIComponent(part)).join("/");
}

function purlQualifiers(entries) {
  const pairs = entries
    .filter(([, value]) => value !== undefined && value !== null && value !== "")
    .map(([key, value]) => `${key}=${encodeURIComponent(value)}`);
  return pairs.length > 0 ? `?${pairs.join("&")}` : "";
}

function property(name, value) {
  return { name: `pdf-tools:${name}`, value };
}

/**
 * Classifies every notice the runtime ships. Throws on anything unrecognised
 * rather than skipping it, so a new bundled licence cannot slip through as an
 * unlisted component.
 */
function classifyNotices(provenance) {
  const notices = provenance.notices.components;
  const components = [];
  const topLevel = [];
  const buildRecipe = [];

  for (const notice of notices) {
    if (notice.component === "pdfium-binaries build scripts") {
      // This is the repository build recipe, not a linked component.
      // It's committed alongside the release notices to attribute the build
      // recipe itself, not part of the release archive.
      buildRecipe.push(notice);
      continue;
    }
    if (notice.component === "PDFium") {
      // Top-level runtime
      topLevel.push(notice);
      continue;
    }
    // Everything else is bundled in the pdfium.dll binary
    components.push(notice);
  }

  if (topLevel.length !== 1) {
    throw new Error("PDFium runtime must have exactly one PDFium component");
  }
  if (components.length === 0) {
    throw new Error("PDFium runtime must have bundled components");
  }
  if (buildRecipe.length !== 1) {
    throw new Error("PDFium runtime must have exactly one build recipe notice");
  }

  return { topLevel: topLevel[0], components, buildRecipe: buildRecipe[0] };
}

function noticeReference(provenance, notice, isBuildRecipe = false) {
  // All license notices are in vendor/pdfium/licenses/, not vendor/pdfium/runtime/.
  // They are shipped alongside the DLLs but are tracked separately from the
  // runtime_assets (which contains only the pdfium.dll binaries).
  const assetPath = `vendor/pdfium/${notice.file}`;

  // For build recipe notices, note that they're for attribution only
  if (isBuildRecipe) {
    return {
      type: "license",
      url: assetPath,
      comment: `${notice.component} (${notice.spdx}); repository build recipe attribution`,
    };
  }

  // For shipped notices, include the hash
  return {
    type: "license",
    url: assetPath,
    comment: `${notice.component} (${notice.spdx})`,
    hashes: [{ alg: "SHA-256", content: notice.sha256 }],
  };
}

/**
 * The composite licence of a statically linked artifact is the conjunction of
 * every licence linked into it: a redistributor has to satisfy all of them.
 * Derived from the shipped notice manifest, with any compound term
 * parenthesised so the result stays a well-formed SPDX expression.
 */
function compositeLicenseExpression(provenance) {
  const expressions = [...new Set(provenance.notices.components.map(notice => notice.spdx))]
    .sort(compareCodePoints)
    .map(expression => (/\s/.test(expression) ? `(${expression})` : expression));
  if (expressions.length === 0) throw new Error("PDFium runtime ships no licence notices");
  return expressions.join(" AND ");
}

function runtimeComponent(provenance) {
  const buildInfo = provenance.build;
  const version = `${buildInfo.pdfium_version}`;

  return {
    type: "library",
    "bom-ref": RUNTIME_BOM_REF,
    group: "pdf-tools",
    name: "pdfium-runtime",
    version,
    scope: "required",
    description:
      `Official Google Chromium PDFium prebuilt binaries from bblanchon/pdfium-binaries, `
      + `shipping Windows platform binaries (win-x64 and win-arm64) at ${RUNTIME_DIRECTORY}/ `
      + `in the MCPB for Windows targets only.`,
    purl: `pkg:generic/pdf-tools/pdfium-runtime@${version}`
      + purlQualifiers([["download_url", buildInfo.upstream_tag]]),
    licenses: [{ expression: compositeLicenseExpression(provenance) }],
    externalReferences: [
      {
        type: "distribution",
        url: buildInfo.upstream_repository,
        comment: `Official PDFium prebuilds from ${buildInfo.upstream_repository} tag ${buildInfo.upstream_tag}`,
      },
    ],
    properties: [
      property("pdfium-artifact-id", provenance.artifact_id),
      property("pdfium-version", buildInfo.pdfium_version),
      property("pdfium-upstream-tag", buildInfo.upstream_tag),
      property("pdfium-upstream-commit", buildInfo.upstream_commit),
      property(
        "pdfium-licence-basis",
        "Conjunction of every notice the runtime ships, because all of them are linked into "
        + "one artifact; each individual licence is attached to the component it actually covers.",
      ),
    ],
  };
}

function bundledComponents(provenance, classified) {
  const bundledAndRecipe = [...classified.components];
  const buildRecipeRef = noticeReference(provenance, classified.buildRecipe, true);

  return bundledAndRecipe.map(notice => ({
    type: "library",
    "bom-ref": `urn:pdf-tools:pdfium-bundled:${notice.component}`,
    name: notice.component,
    version: notice.component.includes(" ") ? notice.component.split(" ").pop() : "embedded",
    scope: "required",
    description: `${notice.component}; statically linked into ${RUNTIME_DIRECTORY}/pdfium.dll (Windows platforms only).`,
    licenses: [{ expression: notice.spdx }],
    externalReferences: [
      noticeReference(provenance, notice),
    ],
    properties: [
      property("pdfium-linkage", `statically linked into ${RUNTIME_DIRECTORY}/pdfium.dll`),
    ],
  })).concat([{
    type: "library",
    "bom-ref": `urn:pdf-tools:pdfium-build-recipe`,
    name: classified.buildRecipe.component,
    scope: "required",
    description: `${classified.buildRecipe.component}; repository build recipe used to download and promote the runtime, committed for attribution.`,
    licenses: [{ expression: classified.buildRecipe.spdx }],
    externalReferences: [buildRecipeRef],
    properties: [
      property("pdfium-role", "build-recipe-attribution; not redistributed, only committed for provenance"),
    ],
  }]);
}

/**
 * Every CycloneDX component the PDFium runtime contributes, sorted
 * by `bom-ref` so the generated SBOM is byte-stable.
 */
export function derivePdfiumSbomComponents(provenance = PDFIUM_RUNTIME_PROVENANCE) {
  const classified = classifyNotices(provenance);
  const components = [
    runtimeComponent(provenance),
    ...bundledComponents(provenance, classified),
  ].sort((left, right) => compareCodePoints(left["bom-ref"], right["bom-ref"]));
  const refs = new Set(components.map(component => component["bom-ref"]));
  if (refs.size !== components.length) {
    throw new Error("PDFium SBOM components contain a duplicate bom-ref");
  }
  return components;
}

/**
 * Dependency edges for the PDFium components. The runtime is the artifact that
 * ships, and bundled components hang off it.
 */
export function derivePdfiumSbomDependencies(components) {
  const childRefs = components
    .map(component => component["bom-ref"])
    .filter(ref => ref !== RUNTIME_BOM_REF)
    .sort(compareCodePoints);
  return [
    { ref: RUNTIME_BOM_REF, dependsOn: childRefs },
    ...childRefs.map(ref => ({ ref, dependsOn: [] })),
  ];
}

export const PDFIUM_SBOM_COMPONENTS = Object.freeze(derivePdfiumSbomComponents());
export const PDFIUM_SBOM_DEPENDENCIES = Object.freeze(
  derivePdfiumSbomDependencies(PDFIUM_SBOM_COMPONENTS),
);
export const PDFIUM_RUNTIME_COMPONENT_BOM_REF = RUNTIME_BOM_REF;
